### ISSUE TITLE
Response not correct when @ is the first character

### ISSUE THREAD

**Issue by vaindil** [phenax/f-inator-3000#1]
If I enter `the cat`, it's properly turned into `the fucking cat`. Using `!the cat` becomes `!the fucking cat`. All other variants I tried work, except `@`. Using `@the cat` returns `fucking @the cat`.

(fucking piece of shit couldn't even write an app properly)

( <3 )

**Comment by bartl1jp** [comment]
Actually `#test` doesn't work either.

**Comment by phenax** [comment]
The reason `@the cat` doesnt work is because of the fact that its not fucking english. But thanx for reporting. Will fix it. XD

**Comment by vaindil** [comment]
Are you trying to tell me how to write? Jeez. Also I don't think Thomas will appreciate that you mentioned him. ;)

**Comment by phenax** [comment]
Fuck! XD. Sorry thomas.
